import type { StoreItem, StoreType } from "@grim-frontier/shared"

/** Seed definition for a store, including the landmark key it belongs to. */
export interface StoreSeed {
  landmarkKey: string
  name: string
  type: StoreType
  description: string
  proprietor: string
  inventory: StoreItem[]
}

/** All default stores seeded into new worlds. */
export const storeSeedData: StoreSeed[] = [
  {
    landmarkKey: "dustercreek",
    name: "Dustercreek Trading Post",
    type: "general_store",
    description:
      "The beating heart of any frontier settlement. Dustercreek Trading Post stocks the essentials that keep a camp alive and a body working. Proprietor keeps a running tab for regulars, though he's not known for his patience.",
    proprietor: "Hector Ridley",
    inventory: [
      { name: "Flour, 50lb sack", price: 0.9, category: "provisions", weight: 50.0 },
      { name: "Salt pork, per lb", price: 0.08, category: "provisions", weight: 1.0 },
      { name: "Hardtack biscuits, per dozen", price: 0.15, category: "provisions", weight: 1.5 },
      { name: "Canned peaches", price: 0.12, category: "provisions", weight: 1.8 },
      { name: "Canned pinto beans", price: 0.08, category: "provisions", weight: 1.7 },
      { name: "Canned tomatoes", price: 0.1, category: "provisions", weight: 1.8 },
      { name: "Canned condensed milk", price: 0.14, category: "provisions", weight: 1.4 },
      { name: "Arbuckle's Ariosa Coffee, 1lb", price: 0.28, category: "provisions", weight: 1.0 },
      { name: "Granulated sugar, per lb", price: 0.06, category: "provisions", weight: 1.0 },
      { name: "Molasses, per quart", price: 0.18, category: "provisions", weight: 2.8 },
      { name: "Candle tallow, per dozen", price: 0.22, category: "household", weight: 1.2 },
      { name: "Coal oil lantern", price: 1.1, category: "household", weight: 2.4 },
      { name: "Lantern oil, per gallon", price: 0.15, category: "household", weight: 8.5 },
      { name: "Manila rope, per 50ft", price: 0.85, category: "household", weight: 6.0 },
      { name: "Wool blanket", price: 1.25, category: "household", weight: 4.5 },
      { name: "Muslin cloth, per yard", price: 0.08, category: "household", weight: 0.4 },
      { name: "Denim duck cloth, per yard", price: 0.14, category: "household", weight: 0.8 },
      { name: "Wrought iron nails, per lb", price: 0.07, category: "tools", weight: 1.0 },
      { name: "Hand saw", price: 1.4, category: "tools", weight: 2.2 },
      { name: "Wooden-handled hammer", price: 0.65, category: "tools", weight: 1.8 },
      { name: "Axe handle, replacement", price: 0.35, category: "tools", weight: 2.5 },
      { name: "Tin cup", price: 0.1, category: "household", weight: 0.4 },
      { name: "Cast iron skillet", price: 0.75, category: "household", weight: 4.8 },
    ],
  },
  {
    landmarkKey: "dustercreek",
    name: "Graves Ironworks",
    type: "blacksmith",
    description:
      "The smell of coal smoke and hot iron marks Graves Ironworks from two streets away. Silas Graves is a man of few words and extraordinary hands. He does not rush, and he does not apologize for it.",
    proprietor: "Silas Graves",
    inventory: [
      { name: "Horseshoe, per set of four", price: 0.8, category: "farrier", weight: 4.0 },
      { name: "Horseshoeing, labor", price: 0.5, category: "services" },
      { name: "Wagon wheel rim, replace", price: 2.25, category: "services" },
      { name: "Wagon axle repair", price: 1.75, category: "services" },
      { name: "Single bit felling axe", price: 1.1, category: "tools", weight: 4.5 },
      { name: "Double bit axe", price: 1.65, category: "tools", weight: 5.2, traits: ["Chop Wood"] },
      { name: "Pick mattock", price: 1.4, category: "tools", weight: 6.8 },
      { name: "Miner's pickaxe", price: 1.2, category: "tools", weight: 6.2 },
      { name: "Hay fork", price: 0.9, category: "tools", weight: 4.0 },
      { name: "Draw knife", price: 0.75, category: "tools", weight: 1.4 },
      { name: "Cold chisel", price: 0.45, category: "tools", weight: 0.8 },
      { name: "Branding iron, custom", price: 2.5, category: "custom", weight: 3.5 },
      { name: "Tool sharpening", price: 0.15, category: "services" },
      { name: "General tool repair", price: 0.25, category: "services", description: "Prices vary by condition" },
      { name: "Wrought iron chain, per ft", price: 0.12, category: "hardware", weight: 1.2 },
      { name: "Door hinges, per pair", price: 0.3, category: "hardware", weight: 0.6 },
    ],
  },
  {
    landmarkKey: "dustercreek",
    name: "Lucky Barrel Saloon",
    type: "saloon",
    description:
      "Low ceiling, lower morals. The Lucky Barrel is where deals get made and men get unmade. The house whiskey has been known to cause temporary blindness. The gambling is not rigged, exactly, but the house has never gone hungry.",
    proprietor: "Dutch Lorrigan",
    inventory: [
      { name: "Red Eye whiskey, glass", price: 0.1, category: "drinks", weight: 0.6 },
      { name: "Kentucky bourbon, glass", price: 0.25, category: "drinks", weight: 0.6 },
      { name: "Bottled whiskey, house", price: 0.75, category: "drinks", weight: 2.8 },
      { name: "Bottled whiskey, imported", price: 1.5, category: "drinks", weight: 2.8 },
      { name: "Lager beer, mug", price: 0.05, category: "drinks", weight: 1.4 },
      { name: "Warm stew and bread", price: 0.2, category: "meals", weight: 1.8 },
      { name: "Beefsteak and beans", price: 0.35, category: "meals", weight: 1.2 },
      { name: "Faro, per hand", price: 0.1, category: "entertainment", description: "Minimum bet" },
      { name: "Poker, per hand", price: 0.25, category: "entertainment", description: "Minimum bet" },
      { name: "Job board posting", price: 0.1, category: "services" },
      { name: "Private back room, per hour", price: 0.5, category: "services" },
    ],
  },
  {
    landmarkKey: "dustercreek",
    name: "Three Pines Livery Stable",
    type: "livery",
    description:
      "Cleaner than most saloons and quieter than any of them. Emmett Thole runs a tight stable — horses are fed on schedule and treated better than most men in this territory. He remembers every animal that's passed through.",
    proprietor: "Emmett Thole",
    inventory: [
      { name: "Horse boarding, per night", price: 0.35, category: "boarding" },
      { name: "Horse boarding, per week", price: 2.0, category: "boarding" },
      { name: "Draft horse rental, per day", price: 1.5, category: "rental" },
      { name: "Saddle horse rental, per day", price: 1.0, category: "rental" },
      { name: "Wagon storage, per night", price: 0.25, category: "boarding" },
      { name: "Wagon storage, per week", price: 1.25, category: "boarding" },
      { name: "Oat feed, per day", price: 0.2, category: "feed", weight: 12.0 },
      { name: "Hay feed, per day", price: 0.1, category: "feed", weight: 20.0 },
      { name: "Grooming and brushdown", price: 0.25, category: "services" },
      { name: "Saddle, working stock", price: 18.0, category: "tack", weight: 28.0 },
      { name: "Bridle and bit", price: 3.5, category: "tack", weight: 3.2 },
      { name: "Saddlebags, leather pair", price: 4.25, category: "tack", weight: 4.5 },
      { name: "Horseshoe inspection", price: 0.1, category: "services" },
    ],
  },
  {
    landmarkKey: "dustercreek",
    name: "Braddock Arms",
    type: "gunsmith",
    description:
      "Walt Braddock built his reputation on one principle: a gun that misfires gets a man killed. Everything in the shop has been inspected, cleaned, and warranted by his hand. He will not sell a weapon he does not trust, and he will not rush a repair.",
    proprietor: "Walt Braddock",
    inventory: [
      { name: "Colt Single Action Army revolver", price: 17.0, category: "firearms", weight: 2.3 },
      { name: "Remington 1875 revolver", price: 15.5, category: "firearms", weight: 2.6 },
      { name: "Smith & Wesson Schofield", price: 14.0, category: "firearms", weight: 2.4 },
      { name: "Winchester Model 1873 rifle", price: 28.0, category: "firearms", weight: 8.5 },
      { name: "Springfield Trapdoor carbine", price: 22.0, category: "firearms", weight: 7.8 },
      { name: "Double-barrel shotgun", price: 19.5, category: "firearms", weight: 8.2 },
      { name: ".45 Colt cartridges, per 50", price: 1.1, category: "ammunition", weight: 1.4 },
      { name: ".44-40 cartridges, per 50", price: 1.05, category: "ammunition", weight: 1.3 },
      { name: "12 gauge shells, per 25", price: 0.75, category: "ammunition", weight: 1.8 },
      { name: "Percussion caps, per 100", price: 0.4, category: "ammunition", weight: 0.3 },
      { name: "Gun cleaning kit", price: 0.85, category: "accessories", weight: 0.8 },
      { name: "Holster, plain leather", price: 2.5, category: "accessories", weight: 0.6 },
      { name: "Holster, tooled leather", price: 5.0, category: "accessories", weight: 0.7 },
      { name: "Gun belt", price: 3.25, category: "accessories", weight: 0.9 },
      { name: "General gun repair", price: 0.5, category: "services", description: "Prices vary by work required" },
      { name: "Action job / timing", price: 2.0, category: "services" },
      { name: "Barrel replacement", price: 5.0, category: "services", description: "Starting price" },
    ],
  },
  {
    landmarkKey: "dustercreek",
    name: "Dr. Calder's Remedies",
    type: "doctor",
    description:
      "Dr. Erasmus Calder trained in Philadelphia and ended up here, which tells you something about either his ambition or his luck. His remedies are genuine, his surgery is competent, and he will not discuss how he came to know quite so much about gunshot wounds.",
    proprietor: "Dr. Erasmus Calder",
    inventory: [
      { name: "Medical consultation", price: 0.5, category: "services" },
      { name: "Wound treatment, minor", price: 1.0, category: "services" },
      { name: "Wound treatment, serious", price: 3.0, category: "services", description: "Prices vary by severity" },
      { name: "Tooth extraction", price: 0.5, category: "services" },
      { name: "Laudanum tincture, per bottle", price: 0.45, category: "medicines", weight: 0.8 },
      { name: "Carbolic acid, antiseptic", price: 0.3, category: "medicines", weight: 0.6 },
      { name: "Castor oil, per bottle", price: 0.2, category: "medicines", weight: 0.7 },
      { name: "Quinine sulfate, fever", price: 0.6, category: "medicines", weight: 0.4 },
      { name: "Morphine powder", price: 0.75, category: "medicines", weight: 0.2 },
      { name: "Willow bark tincture", price: 0.25, category: "medicines", weight: 0.5 },
      { name: "Calendula salve", price: 0.2, category: "medicines", weight: 0.4 },
      { name: "Dried valerian root", price: 0.18, category: "medicines", weight: 0.3 },
      { name: "Linen bandage roll", price: 0.15, category: "supplies", weight: 0.4 },
      { name: "Surgical suture kit", price: 1.25, category: "supplies", weight: 0.6 },
      { name: "Cod liver oil, per bottle", price: 0.35, category: "medicines", weight: 0.8 },
      { name: "Carter's Little Liver Pills", price: 0.25, category: "medicines", weight: 0.2 },
    ],
  },
  {
    landmarkKey: "dustercreek",
    name: "Wayward Rest Hotel",
    type: "hotel",
    description:
      "Three stories of weathered pine and wishful thinking. The Wayward Rest caters to travelers who need a roof and a mattress, nothing more. The walls are thin. The guests talk. Management considers this a feature.",
    proprietor: "Maude Pickering",
    inventory: [
      { name: "Common room bunk, per night", price: 0.15, category: "lodging" },
      { name: "Single room, per night", price: 0.5, category: "lodging" },
      { name: "Single room, per week", price: 2.5, category: "lodging" },
      { name: "Bath, hot water", price: 0.25, category: "services" },
      { name: "Breakfast, eggs and salt pork", price: 0.2, category: "meals", weight: 0.8 },
      { name: "Supper, stew and biscuits", price: 0.25, category: "meals", weight: 1.4 },
      { name: "Laundry service", price: 0.35, category: "services" },
    ],
  },
  {
    landmarkKey: "wayward",
    name: "Valley Road House",
    type: "roadhouse",
    description:
      "Built at the junction where three trails cross, the Valley Road House has seen everything come through its doors at least twice. The proprietress, a widow named Clara Foss, keeps a shotgun behind the bar and a Bible on the counter. She uses both.",
    proprietor: "Clara Foss",
    inventory: [
      { name: "Shared bunkroom, per night", price: 0.1, category: "lodging" },
      { name: "Private room, per night", price: 0.4, category: "lodging" },
      { name: "Private room, per week", price: 2.0, category: "lodging" },
      { name: "Bath, cold water", price: 0.1, category: "services" },
      { name: "Bath, hot water", price: 0.2, category: "services" },
      { name: "Breakfast, corn porridge", price: 0.1, category: "meals", weight: 0.7 },
      { name: "Supper, beans and bread", price: 0.15, category: "meals", weight: 1.0 },
      { name: "Supper, roast and potatoes", price: 0.3, category: "meals", weight: 1.4 },
      { name: "Feed and water for horse", price: 0.15, category: "services" },
    ],
  },
  {
    landmarkKey: "dustercreek",
    name: "Red River Butchery",
    type: "butcher",
    description:
      "Elias Cord has been breaking down cattle since he was twelve years old. The Red River Butchery is not a pleasant place but it is an honest one. The cuts are fair, the scale is true, and Cord throws in the bones for dogs and soup stock without being asked.",
    proprietor: "Elias Cord",
    inventory: [
      { name: "Beef brisket, per lb", price: 0.08, category: "fresh cuts", weight: 1.0 },
      { name: "Beef chuck, per lb", price: 0.07, category: "fresh cuts", weight: 1.0 },
      { name: "Beef liver, per lb", price: 0.04, category: "fresh cuts", weight: 1.0 },
      { name: "Pork belly, per lb", price: 0.07, category: "fresh cuts", weight: 1.0 },
      { name: "Pork ribs, per rack", price: 0.35, category: "fresh cuts", weight: 4.5 },
      { name: "Salt pork, cured, per lb", price: 0.09, category: "preserved", weight: 1.0 },
      { name: "Beef jerky, per lb", price: 0.22, category: "preserved", weight: 1.0 },
      { name: "Pork jerky, per lb", price: 0.2, category: "preserved", weight: 1.0 },
      { name: "Smoked sausage links, per lb", price: 0.14, category: "preserved", weight: 1.0 },
      { name: "Tallow, rendered, per lb", price: 0.05, category: "rendered", weight: 1.0 },
      { name: "Bone broth stock, per quart", price: 0.08, category: "rendered", weight: 2.2 },
      { name: "Whole dressed chicken", price: 0.3, category: "fresh cuts", weight: 3.5 },
      { name: "Bulk order, side of beef", price: 8.0, category: "bulk", description: "Prices vary by weight" },
    ],
  },
  {
    landmarkKey: "dustercreek",
    name: "Hawthorne Tailoring",
    type: "tailor",
    description:
      "The only establishment in Dustercreek where a man can walk in looking like a drifter and walk out looking like he owns something. Nathaniel Hawthorne does not judge his customers. He has, however, been known to charge more for people he doesn't like.",
    proprietor: "Nathaniel Hawthorne",
    inventory: [
      { name: "Canvas work trousers", price: 1.1, category: "clothing", weight: 1.4 },
      { name: "Wool broadcloth trousers", price: 2.5, category: "clothing", weight: 1.8 },
      { name: "Cotton work shirt", price: 0.75, category: "clothing", weight: 0.6 },
      { name: "Flannel shirt", price: 1.0, category: "clothing", weight: 0.8 },
      { name: "Wool vest", price: 1.75, category: "clothing", weight: 0.9 },
      { name: "Oilskin duster coat", price: 5.5, category: "clothing", weight: 4.2 },
      { name: "Wool greatcoat", price: 8.0, category: "clothing", weight: 5.8 },
      { name: "Leather work gloves", price: 0.65, category: "accessories", weight: 0.4 },
      { name: "Wool driving gloves", price: 1.1, category: "accessories", weight: 0.3 },
      { name: "Felt slouch hat", price: 1.25, category: "hats", weight: 0.4 },
      { name: "Stiff-brim plainsman hat", price: 2.0, category: "hats", weight: 0.6 },
      { name: "Leather boots, work", price: 3.5, category: "footwear", weight: 3.2 },
      { name: "Leather boots, riding", price: 5.5, category: "footwear", weight: 3.8 },
      { name: "Garment repair, minor", price: 0.15, category: "services" },
      { name: "Garment repair, major", price: 0.5, category: "services" },
      { name: "Custom tailoring, per garment", price: 2.0, category: "services", description: "Starting price" },
    ],
  },
  {
    landmarkKey: "dustercreek",
    name: "Dustercreek Freight & Co.",
    type: "freight",
    description:
      "The lifeblood of commerce in the territory. If it moves between settlements, it moves through Dustercreek Freight. The clerks know every road, every route, every gang that's been working the passes. That knowledge costs extra.",
    proprietor: "Amos Pritchard",
    inventory: [
      { name: "Local freight delivery, per 100lb", price: 0.75, category: "shipping" },
      { name: "Regional freight, per 100lb", price: 2.0, category: "shipping" },
      { name: "Express mail, per letter", price: 0.05, category: "mail", weight: 0.1 },
      { name: "Parcel post, per lb", price: 0.12, category: "mail", weight: 1.0 },
      { name: "Freight contract, negotiated", price: 5.0, category: "contracts", description: "Starting price" },
      { name: "Bonded cargo insurance", price: 0.05, category: "contracts", description: "5% of cargo value" },
      { name: "Secure strongbox transport", price: 3.0, category: "shipping", description: "Starting price" },
      { name: "Route information", price: 0.25, category: "services" },
      { name: "Wagon hire with driver", price: 4.0, category: "rental", description: "Per day" },
    ],
  },
]
